export { default as Terms } from './terms/terms'
export { default as Timeline } from './timeline/timeline'
export { default as Team } from './team/team'
export { default as Metrics } from './metrics/metrics'

export { default as ConsignedCarousel } from './consigned-carousel/consigned-carousel'
export { default as FgtsSimulation } from './fgts-simulation/fgts-simulation'
export { default as HeaderPolicy } from './header-policy/header-policy'
export { default as IntranetDisplay } from './intranet/intranet-display'
export { default as LoanBenefits } from './loan-benefits/loan-benefits'
export { default as LoanCarousel } from './loan-carousel/loan-carousel'
export { default as LoanWarning } from './loan-warning/loan-warning'
