export { default as Benefits } from './benefits/benefits'
export { default as Faq } from './faq/faq'
export { default as Header } from './header/header'
export { default as InfoPanel } from './info-panel/info-panel'
export { default as LatestPosts } from './latest-posts/latest-posts'
export { default as LoadInfo } from './load-info/load-info'
export { default as PartnersBanks } from './partners-banks/partners-banks'
