export * from './privacy-policy'
export * from './blog'
export * from './partners'
export * from './terms-of-use'
export * from './personal-loan'
export * from './sign-in'
export * from './payroll-loan'
export * from './fgts-loan'
