import FOUNDER from './FOUNDER.webp'
import CONFRATERNIZACAO_TROFEU from './CONFRATERNIZACAO_TROFEU.webp'
import PESSOA_OLHANDO_PRA_VOCÊ from './PESSOA_OLHANDO_PRA_VOCÊ.webp'
import QUEM_SOMOS from './QUEM_SOMOS.webp'
import EQUIPE_TODOS_AMARELO from './EQUIPE_TODOS_AMARELO.webp'
import FOUNDER_CONFRATERNIZACAO from './FOUNDER_CONFRATERNIZACAO.webp'
import EQUIPE_TODOS_VERMELHO from './EQUIPE_TODOS_VERMELHO.webp'
import EQUIPE_UNIDA from './EQUIPE_TODOS_AMARELO.webp'
import LOGO_AMERICA_PARTNERS from './LOGO_AMERICA_PARCEIROS.webp'
import IDOSO_REALIZANDO_EMPRESTIMO from './IDOSO_REALIZANDO_EMPRESTIMO.webp'
import CASA_DOS_SONHOS from './CASA_DOS_SONHOS.webp'
import AUMENTAR_LUCRO from './AUMENTAR_LUCRO.webp'
import BANCO_BANRISUL from './BANCO_BANRISUL.webp'
import BANCO_BRADESCO from './BANCO_BRADESCO.webp'
import BANCO_CAIXA from './BANCO_CAIXA.webp'
import BANCO_SAFRA from './BANCO_SAFRA.webp'
import BANCO_PAN from './BANCO_PAN.webp'
import BANCO_SANTANDER from './BANCO_SANTANDER.webp'
import BANCO_C6 from './BANCO_C6.webp'
import BANCO_ITAU from './BANCO_ITAU.webp'
import EMPRESTIMO_CONSIGNADO_APOSENTADOS from './EMPRESTIMO_CONSIGNADO_APOSENTADOS.webp'
import CARTAO_CREDITO from './CARTAO_CREDITO.webp'
import CRESCIMENTO_EMPRESA from './CRESCIMENTO_EMPRESA.webp'
import PAGAR_DIVIDAS from './PAGAR_DIVIDAS.webp'
import EDUCACAO from './EDUCACAO.webp'
import EMPRESTIMO_ADULTOS_CONVERSANDO from './EMPRESTIMO_ADULTOS_CONVERSANDO.webp'
import IMPULSIONE_RECEITA from './IMPULSIONANDO_RECEITA.webp'
import INVESTIMENTOS from './INVESTIMENTOS.webp'
import MOVEIS from './MOVEIS.webp'
import PARCEIROS from './PARCEIROS.webp'
import SAUDE from './SAUDE.webp'
import SONHO from './SONHO.webp'
import VIAGEM from './VIAGEM.webp'
import BANCO_BRASIL from './BANCO_BRASIL.webp'
import CONTE_CONOSCO from './CONTE_CONOSCO.webp'
import DUAS_PESSOAS_CONVERSANDO from './DUAS_PESSOAS_CONVERSANDO.webp'
import LOGO_AMERICA_FINANCEIRA_SEGURO from './LOGO_AMERICA_FINANCEIRA_SEGURO.webp'
import LOGO_AMERICA_LETRAS_AZUL from './LOGO_AMERICA_LETRAS_AZUL.webp'

const IMAGE = {
  LOGO_AMERICA_LETRAS_AZUL,
  FOUNDER,
  CONFRATERNIZACAO_TROFEU,
  PESSOA_OLHANDO_PRA_VOCÊ,
  QUEM_SOMOS,
  EQUIPE_TODOS_AMARELO,
  FOUNDER_CONFRATERNIZACAO,
  EQUIPE_TODOS_VERMELHO,
  EQUIPE_UNIDA,
  LOGO_AMERICA_PARTNERS,
  IDOSO_REALIZANDO_EMPRESTIMO,
  CASA_DOS_SONHOS,
  AUMENTAR_LUCRO,
  BANCO_BANRISUL,
  BANCO_BRADESCO,
  BANCO_CAIXA,
  BANCO_SAFRA,
  BANCO_PAN,
  BANCO_SANTANDER,
  LOGO_AMERICA_FINANCEIRA_SEGURO,
  BANCO_C6,
  BANCO_ITAU,
  EMPRESTIMO_CONSIGNADO_APOSENTADOS,
  CARTAO_CREDITO,
  CRESCIMENTO_EMPRESA,
  PAGAR_DIVIDAS,
  EDUCACAO,
  EMPRESTIMO_ADULTOS_CONVERSANDO,
  IMPULSIONE_RECEITA,
  INVESTIMENTOS,
  MOVEIS,
  PARCEIROS,
  SAUDE,
  SONHO,
  VIAGEM,
  BANCO_BRASIL,
  CONTE_CONOSCO,
  DUAS_PESSOAS_CONVERSANDO,
}

export default IMAGE
