import {
  IconX,
  IconCaretUp,
  IconUser,
  IconBrandWhatsapp,
  IconArrowRight,
  IconMenu3,
  IconBrandLinkedin,
  IconBrandInstagram,
  IconPlus,
  IconMinus,
  IconCaretDown,
  IconBrandYoutube,
  IconBrandFacebook,
  IconArrowLeft,
  IconCurrencyDollar,
  IconChartLine,
  IconUsers,
  IconCalendarMonth,
} from '@tabler/icons-react'

const ICON = {
  IconBrandFacebook,
  IconCaretUp,
  IconCaretDown,
  IconUser,
  IconPlus,
  IconMinus,
  IconCurrencyDollar,
  IconChartLine,
  IconUsers,
  IconCalendarMonth,
  IconX,
  IconMenu3,
  IconBrandInstagram,
  IconBrandLinkedin,
  IconBrandWhatsapp,
  IconArrowLeft,
  IconArrowRight,
  IconBrandYoutube,
}

export default ICON
