export { default as Banks } from './banks/banks'
export { default as Navbar } from './navbar/navbar'
export { default as NavMobile } from './navbar/nav-mobile'
export { default as Footer } from './footer/footer'
export { default as Header } from './header/header'

export { default as ArticleHeader } from './article-header/article-header'
export { default as NavItem } from './navbar/nav-item'
export { default as Benefits } from './benefits/benefits'
export { default as Faq } from './faq/faq'
export { default as FollowUs } from './follow-us/follow-us'
export { default as InfoPanel } from './info-panel/info-panel'
export { default as Information } from './information/information'
export { default as LatestPosts } from './latest-posts/latest-posts'
export { default as LoadInfo } from './load-info/load-info'
